# Site settings
title:       Really Wanamaker
email:       mwanamaker@icloud.com
author:      Matthew Wanamaker
description: "I'm just a plain text guy living in an emoji world"
baseurl:     ""
url:         "http://matthewwanamaker.com"
date_format: "%b %-d, %Y"

# Gems
gems: [jekyll-paginate]

# Google analytics
# Google services
google_analytics: 
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: reallywanamaker
bitbucket_username:
stackoverflow_id:
twitter_username: reallywanamaker
google_plus_id:
linkedin_username: mwanamaker
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
